#!/usr/bin/perl

use File::Basename 'dirname';
use File::Spec;

use constant APP_PATH =>
  join '/', File::Spec->splitdir(dirname(__FILE__)), '..';

use lib APP_PATH . '/lib';
use Koala;

Koala->start;
