#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib", "/home/bugov/perl5/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/" }

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Koala');
